require "rails_helper"

RSpec.describe ReferralCode, type: :model do
  describe "associations" do
    it { is_expected.to have_many(:referrals).dependent(:restrict_with_error) }
    it { is_expected.to have_many(:businesses).dependent(:nullify) }
  end

  describe "validations" do
    subject { build(:referral_code) }

    # code is auto-generated by before_validation callback when blank,
    # so validate_presence_of cannot be tested with shoulda-matchers
    it "auto-generates a code when blank" do
      rc = build(:referral_code, code: "")
      rc.valid?
      expect(rc.code).to be_present
    end
    it { is_expected.to validate_uniqueness_of(:code).case_insensitive }
    it { is_expected.to validate_presence_of(:referrer_name) }
    it { is_expected.to validate_numericality_of(:commission_percentage).is_greater_than(0).is_less_than_or_equal_to(100) }
  end

  describe "enums" do
    it { is_expected.to define_enum_for(:status).with_values(active: 0, inactive: 1) }
  end

  describe "scopes" do
    describe ".active" do
      let!(:active_code)   { create(:referral_code, status: :active) }
      let!(:inactive_code) { create(:referral_code, status: :inactive) }

      it "returns only active codes" do
        expect(described_class.active).to include(active_code)
        expect(described_class.active).not_to include(inactive_code)
      end
    end
  end

  describe "auto-generate code" do
    it "generates a code when blank on create" do
      code = create(:referral_code, code: nil)
      expect(code.code).to be_present
      expect(code.code.length).to eq(8)
    end

    it "does not overwrite an existing code" do
      code = create(:referral_code, code: "MYCODE")
      expect(code.code).to eq("MYCODE")
    end
  end
end
