# examples:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_cleanup_with_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day

production:
  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12

  reminder_scheduler:
    class: AppointmentReminderSchedulerJob
    queue: default
    schedule: every day at 8am

  token_cleanup:
    class: CleanupExpiredTokensJob
    queue: low
    schedule: every sunday at 3am

  generate_payment_orders:
    class: GenerateSubscriptionPaymentOrdersJob
    queue: default
    schedule: every day at 1am

  check_expired_subscriptions:
    class: CheckExpiredSubscriptionsJob
    queue: default
    schedule: every day at 12:05am

  subscription_reminder:
    class: SendSubscriptionReminderJob
    queue: default
    schedule: every day at 9am

  complete_appointments:
    class: CompleteAppointmentsJob
    queue: default
    schedule: every 15 minutes

  cleanup_request_logs:
    class: CleanupOldRequestLogsJob
    queue: low
    schedule: every sunday at 4am
